name: churn_analysis
# Name of the Conda environment.
# This is the environment where all the required packages for the project will be installed.


channels:
  - defaults
# List of channels to search for packages.
# 'defaults' is the default Conda channel.

dependencies:
  - python=3.8
  # Specifies the Python version to use in the environment.
  # This project uses Python 3.8.

  - numpy
  # NumPy is used for numerical computing.

  - pandas
  # Pandas is used for data manipulation and analysis.

  - scikit-learn
  # Scikit-learn is used for machine learning algorithms and data preprocessing.

  - matplotlib
  # Matplotlib is used for creating static, animated, and interactive visualizations in Python.

  - seaborn
  # Seaborn is used for statistical data visualization, built on top of Matplotlib.

  - jupyter
  # Jupyter is used to create and share documents that contain live code, equations, visualizations, and narrative text.

  - notebook
  # Notebook is a package that provides the Jupyter notebook application.

  - missingno
  # Missingno is used for visualizing missing data.

  - category_encoders
  # Category Encoders is used for encoding categorical variables.

  - joblib
  # Joblib is used for lightweight pipelining in Python, particularly for loading and saving models.

  - ipywidgets
  # Ipywidgets is used for creating interactive HTML widgets for Jupyter notebooks and the IPython kernel.

  - pip:
      - tensorflow
      # TensorFlow is an open-source platform for machine learning.
      
      - keras
      # Keras is an open-source software library that provides a Python interface for artificial neural networks.
      
      - torch
      # PyTorch is an open-source machine learning library based on the Torch library.
